### ISSUE TITLE
Undefined discriminator for message type Exceptions 

### ISSUE THREAD

**Issue by Dead2** [KnightMiner/UnnaturalAbsorption#4]
Using (among others):
forge-1.12.2-14.23.5.2801-universal.jar
unnatural_absorption-1.12-1.3.1.jar

I keep getting the following printed on the server repeatedly, seemingly each time a user logs in or moves to a new dimension.
Might it just be incompatible with the newer Forge versions?

It does seem to work though, but I am uncertain whether that is an illusion or not.

```
[19:06:27] [Server thread/INFO] [minecraft/DedicatedServer]: XXUsername drowned
[19:06:29] [Server thread/INFO] [journeymap]: XXUsername joining dimension 0
[19:06:29] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type toast.naturalAbsorption.networ                                               k.MessageSyncShield in channel NA|CH1
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar                                               :?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.1                                               2.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.ja                                               r:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.ja                                               r:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper                                               .class:?]
        at toast.naturalAbsorption.EventHandler.onEntityJoinWorld(EventHandler.java:115) [EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1610_EventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynam                                               ic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1206) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
        at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:585) [pl.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:1119) [pa.class:?]
        at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:31) [lb.class:?]
        at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:8) [lb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type toast.naturalAbsorption.network.MessageSyncShield in channel                                                NA|CH1
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexe                                               dMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
        ... 28 more
> Jan 28, 2019 7:06:29 PM io.netty.channel.embedded.EmbeddedChannel recordException
WARNING: More than one exception was raised. Will report only the first one and log others.
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type toast.naturalAbsorption.networ                                               k.MessageSyncShield in channel NA|CH1
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250)
        at toast.naturalAbsorption.EventHandler.onEntityJoinWorld(EventHandler.java:115)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1610_EventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynam                                               ic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraft.world.World.func_72838_d(World.java:1206)
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
        at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:585)
        at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:1119)
        at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:31)
        at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:8)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Undefined discriminator for message type toast.naturalAbsorption.network.MessageSyncShield in channel                                                NA|CH1
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76)
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
        ... 28 more

```

**Comment by KnightMiner** [comment]
Is this only on the server, or also in single player? Probably just something that got lost in the port.

**Comment by lays24mc** [comment]
Hi,

I have the same message in my console. It's only server side. I got the same message back then with the mod Journeymap. The developers of this mod fixed it. Maybe they can help you :)

**Comment by KnightMiner** [comment]
I'm no longer maintaining this mod as Father Toast ported the original mod to 1.12. I suggest you switch back to Natural Absorption.
